/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Dibujo;

import Client.Cliente;
import java.awt.BorderLayout;
import java.awt.Window;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.ListModel;
import javax.swing.SwingUtilities;

/**
 *
 * @author anonymous
 */
public class Frame_lista extends javax.swing.JFrame {

    /**
     * Creates new form Frame_lista
     */
//    public Cliente cliente;
//    private ListModel<String> nombre_salas;
    JList lista;
    private boolean cerrar = false;

    public Frame_lista(Cliente cliente) {
        initComponents();
//        this.cliente = cliente;

        numero_salas(cliente);
        lista.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                if (e.getClickCount() == 2) {
                    int index = lista.locationToIndex(e.getPoint());
                    System.out.println("Double clicked on Item " + index);
                    ListModel<String> model = lista.getModel();
//                    System.out.println(model.getElementAt(index));
                    String nombre_sala = model.getElementAt(index);
//                        System.out.println("nombre sala:"+nombre_sala);
                    if (nombre_sala != null) {
                        try {
                            cliente.write(nombre_sala);
                            String sala_unida = cliente.read();
                            String nombre_cliente = cliente.read();
                            cliente.setName_sala(sala_unida);
                            cliente.setName(nombre_cliente);

                            System.out.println("sala unida:" + cliente.getName_sala());
                            System.out.println("nombre cliente:" + cliente.getName());
//                                cerrar = true;
//                                Thread hilo = new Thread(cliente);
//                                hilo.start();

                            cerrar(cliente);
                        } catch (IOException ex) {
                            Logger.getLogger(Frame_lista.class.getName()).log(Level.SEVERE, null, ex);
                        }

                    }

                }
            }

        });
        this.setVisible(true);

    }

    private void cerrar(Cliente cliente) {
        this.setVisible(false);
        Thread hilo = new Thread(cliente);
        hilo.start();
        Ludo ludo = new Ludo("LUDO", cliente);
        Thread hilo2 = new Thread(ludo);
        hilo2.start();

    }

    private void numero_salas(Cliente cliente) {

        try {
            lista = new JList<String>(modelList(cliente));
            lista.setSize(contenedor_lista.getWidth(), contenedor_lista.getHeight());
            contenedor_lista.add(lista, BorderLayout.CENTER);
        } catch (IOException ex) {
            Logger.getLogger(Frame_lista.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private DefaultListModel modelList(Cliente cliente) throws IOException {
        String[] splic = cliente.read().split(",");
        DefaultListModel model = new DefaultListModel<>();
        for (int i = 0; i < splic.length; i++) {
            model.addElement(splic[i]);
        }
        return model;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        contenedor_lista = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("SALAS DEL JUEGO"));

        javax.swing.GroupLayout contenedor_listaLayout = new javax.swing.GroupLayout(contenedor_lista);
        contenedor_lista.setLayout(contenedor_listaLayout);
        contenedor_listaLayout.setHorizontalGroup(
            contenedor_listaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 388, Short.MAX_VALUE)
        );
        contenedor_listaLayout.setVerticalGroup(
            contenedor_listaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 278, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contenedor_lista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contenedor_lista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Frame_lista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Frame_lista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Frame_lista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Frame_lista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Frame_lista().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel contenedor_lista;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
