/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Dibujo;

import Client.Cliente;
import Dibujo.Ludo;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author anonymous
 */
public class Sala extends javax.swing.JFrame {

    /**
     * Creates new form Sala
     */
    private Cliente cliente;

    public Sala() {

        initComponents();
        try {
            cliente = new Cliente("localhost", 8080);
        } catch (IOException ex) {
            Logger.getLogger(Sala.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Contenedor = new javax.swing.JPanel();
        lbl_title = new javax.swing.JLabel();
        Crear_Partida = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Partida_local = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Unirse_partida = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Contenedor.setBackground(new java.awt.Color(102, 102, 102));

        lbl_title.setBackground(new java.awt.Color(153, 153, 255));
        lbl_title.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        lbl_title.setForeground(new java.awt.Color(255, 255, 255));
        lbl_title.setText("LUGO GAME");
        lbl_title.setOpaque(true);

        Crear_Partida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Crear_PartidaMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel1.setText("CREAR PARTIDA");

        javax.swing.GroupLayout Crear_PartidaLayout = new javax.swing.GroupLayout(Crear_Partida);
        Crear_Partida.setLayout(Crear_PartidaLayout);
        Crear_PartidaLayout.setHorizontalGroup(
            Crear_PartidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Crear_PartidaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Crear_PartidaLayout.setVerticalGroup(
            Crear_PartidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Crear_PartidaLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Partida_local.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Partida_localMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel2.setText("PARTIDA LOCAL");

        javax.swing.GroupLayout Partida_localLayout = new javax.swing.GroupLayout(Partida_local);
        Partida_local.setLayout(Partida_localLayout);
        Partida_localLayout.setHorizontalGroup(
            Partida_localLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Partida_localLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Partida_localLayout.setVerticalGroup(
            Partida_localLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Partida_localLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel2)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        Unirse_partida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Unirse_partidaMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel3.setText("UNIRSE A UNA PARTIDA");

        javax.swing.GroupLayout Unirse_partidaLayout = new javax.swing.GroupLayout(Unirse_partida);
        Unirse_partida.setLayout(Unirse_partidaLayout);
        Unirse_partidaLayout.setHorizontalGroup(
            Unirse_partidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Unirse_partidaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        Unirse_partidaLayout.setVerticalGroup(
            Unirse_partidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Unirse_partidaLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout ContenedorLayout = new javax.swing.GroupLayout(Contenedor);
        Contenedor.setLayout(ContenedorLayout);
        ContenedorLayout.setHorizontalGroup(
            ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContenedorLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_title)
                    .addGroup(ContenedorLayout.createSequentialGroup()
                        .addComponent(Crear_Partida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Partida_local, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Unirse_partida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        ContenedorLayout.setVerticalGroup(
            ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContenedorLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lbl_title)
                .addGap(35, 35, 35)
                .addGroup(ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Unirse_partida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Partida_local, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Crear_Partida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(124, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Crear_PartidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Crear_PartidaMouseClicked
        try {
//            this.setVisible(false);

            cliente.write("Crear Sala");
            boolean existe_sala = true;
            String[] salas = cliente.read().split(",");
            String nombre_sala = "";
            while (existe_sala == true) {
                nombre_sala = JOptionPane.showInputDialog(this, "NOMBRE DE LA SALA");
                int cont = 0;
                for (int i = 0; i < salas.length; i++) {
                    if (salas[i].equalsIgnoreCase(nombre_sala)) {
                        cont++;
                    }
                }
                if (cont == 0) {
                    existe_sala = false;
                }
            }
            this.setVisible(false);
            cliente.write(nombre_sala);

            cliente.setName_sala(cliente.read());
            cliente.setName(cliente.read());
            System.out.println(cliente.getName());
            System.out.println(cliente.getName_sala());
            Thread hilo = new Thread(cliente);
            hilo.start();

            Ludo ludo = new Ludo("LUDO", cliente);
            Thread hiloL = new Thread(ludo);
            hiloL.start();
        } catch (IOException ex) {
            Logger.getLogger(Sala.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Crear_PartidaMouseClicked

    private void Partida_localMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Partida_localMouseClicked
        System.out.println("partida local");
    }//GEN-LAST:event_Partida_localMouseClicked

    private void Unirse_partidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Unirse_partidaMouseClicked
        System.out.println("Unirse a sala");

        this.setVisible(false);

        cliente.write("Unirse a Sala");
//        Thread hilo = new Thread(cliente);
//        hilo.start();
        Frame_lista listas = new Frame_lista(cliente);
//        listas.setVisible(true);


    }//GEN-LAST:event_Unirse_partidaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sala.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sala.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sala.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sala.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sala().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Contenedor;
    private javax.swing.JPanel Crear_Partida;
    private javax.swing.JPanel Partida_local;
    private javax.swing.JPanel Unirse_partida;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lbl_title;
    // End of variables declaration//GEN-END:variables
}
