/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Dibujo;

import Client.Cliente;
import Dibujo.Dibujo;
import java.awt.Color;
import java.awt.Image;
import java.io.IOException;
import java.util.Observable;
import java.util.Observer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author anonymous
 */
public class Turno1 extends javax.swing.JPanel implements Observer {

    /**
     * Creates new form Turno1
     *
     */
    private ImageIcon ico;
    private Icon img;
    ;
    private Cliente cliente;

    private Dibujo dibujo;

    private int numero_cliente = 0;
    private boolean turno = false;

    public Turno1(Cliente cliente, Dibujo tabla) {

        initComponents();
        this.cliente = cliente;
        dibujo = tabla;
//        obs = new Observador(dibujo);

        this.cliente.addObserver(this);
        ponerGif_dado();

//        obs.addObserver(tabla);
        panel_jugador.setOpaque(true);
//        actualizar_perfil(cliente.getName());
        panel_jugador.setBackground(Color.RED);
        if (!cliente.getName().equalsIgnoreCase("cliente1")) {
            btn_dice.setVisible(false);
        }
        nombrar_jugador();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_jugador = new javax.swing.JPanel();
        lb_perfil = new javax.swing.JLabel();
        btn_dice = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));

        panel_jugador.setName("panel_perfil"); // NOI18N

        javax.swing.GroupLayout panel_jugadorLayout = new javax.swing.GroupLayout(panel_jugador);
        panel_jugador.setLayout(panel_jugadorLayout);
        panel_jugadorLayout.setHorizontalGroup(
            panel_jugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 53, Short.MAX_VALUE)
        );
        panel_jugadorLayout.setVerticalGroup(
            panel_jugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 39, Short.MAX_VALUE)
        );

        lb_perfil.setText("Jugador");
        lb_perfil.setName("lbl_nombre"); // NOI18N
        lb_perfil.setOpaque(true);

        btn_dice.setBackground(new java.awt.Color(255, 255, 255));
        btn_dice.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_dice.setFocusPainted(false);
        btn_dice.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_diceMouseExited(evt);
            }
        });
        btn_dice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_diceActionPerformed(evt);
            }
        });

        jLabel1.setText("Dado");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText(" TURNO");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panel_jugador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_perfil)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel1))
                    .addComponent(btn_dice, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(324, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_perfil)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panel_jugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_dice, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_diceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_diceActionPerformed

        int dice_number = 0;
        dice_number = (int) (Math.random() * 6 + 1);

//            dibujo.mover(dice_number);
        ImageIcon ico2;
        ico2 = new ImageIcon(getClass().getResource("/Dice/dice" + dice_number + ".png"));

        Icon img2 = new ImageIcon(ico2.getImage().getScaledInstance(50, 50, Image.SCALE_DEFAULT));
        btn_dice.setIcon(img2);
        dibujo.mover(dice_number);

        cliente.write(cliente.getName_sala() + "," + "actualizar perfil" + "," + cliente.getName());


    }//GEN-LAST:event_btn_diceActionPerformed

    private void btn_diceMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_diceMouseExited
        try {
            Thread.sleep(700);
        } catch (InterruptedException ex) {
            Logger.getLogger(Turno1.class.getName()).log(Level.SEVERE, null, ex);
        }
        btn_dice.setIcon(img);
    }//GEN-LAST:event_btn_diceMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_dice;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lb_perfil;
    private javax.swing.JPanel panel_jugador;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable o, Object arg) {
        String mensaje = (String) arg;
        String[] splic = mensaje.split(",");

        System.out.println("mensaje:" + mensaje);
        if (splic[1].equals("comer")) {
            dibujo.comer_peon(splic[2], Integer.parseInt(splic[3]));
        } else {
            if (splic[1].equals("actualizar perfil")) {
                try {
                    Actualizar_perfil(Integer.parseInt(splic[2].trim()));
                } catch (InterruptedException ex) {
                    Logger.getLogger(Turno1.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
//            System.out.println(mensaje);
                dibujo.Actualizar_tablero((String) arg);
//            actualizar_perfil((String) arg);
            }
        }

    }

    private void Actualizar_perfil(int numero_player) throws InterruptedException {

        switch (numero_player) {
            case 1:
                panel_jugador.setBackground(Color.RED);
                if (cliente.getName().equals("cliente1")) {
                    btn_dice.setVisible(true);
                } else {
                    Thread.sleep(700);
                    btn_dice.setVisible(false);
                }

                break;
            case 2:
                panel_jugador.setBackground(Color.GREEN);
                if (cliente.getName().equals("cliente2")) {
                    btn_dice.setVisible(true);
                } else {
                    Thread.sleep(700);
                    btn_dice.setVisible(false);
                }

                break;
            case 3:
                panel_jugador.setBackground(Color.YELLOW);
                if (cliente.getName().equals("cliente3")) {
                    btn_dice.setVisible(true);
                } else {
                    Thread.sleep(700);
                    btn_dice.setVisible(false);
                }

                break;
            case 4:
                panel_jugador.setBackground(Color.BLUE);
                if (cliente.getName().equals("cliente4")) {
                    btn_dice.setVisible(true);
                } else {
                    Thread.sleep(700);
//                    this.isVisible();
                    btn_dice.setVisible(false);
                }

                break;
        }
    }

    private void nombrar_jugador() {

        switch (cliente.getName()) {
            case "cliente1":
//                System.out.println("Rojo");
                lb_perfil.setText("ROJO");
//                panel_jugador.setBackground(Color.RED);
//                System.out.println("Cambio el perfil");
                break;
            case "cliente2":
//                System.out.println("verde");
                lb_perfil.setText("VERDE");
//                panel_jugador.setBackground(Color.GREEN);
                break;
            case "cliente3":
//                System.out.println("amarillo");
                lb_perfil.setText("AMARILLO");
//                panel_jugador.setBackground(Color.YELLOW);
                break;
            case "cliente4":
//                System.out.println("Azul");
                lb_perfil.setText("AZUL");
//                panel_jugador.setBackground(Color.BLUE);
                break;
        }
    }

    private void ponerGif_dado() {
        ico = new ImageIcon(getClass().getResource("/Imagenes/dice_gif.gif"));
        img = new ImageIcon(ico.getImage().getScaledInstance(50, 50, Image.SCALE_DEFAULT));
//        obs.addObserver(tabla);
        btn_dice.setIcon(img);
    }

    private static boolean isNumeric(String cadena) {
        try {
            Integer.parseInt(cadena);
            return true;
        } catch (NumberFormatException nfe) {
            return false;
        }
    }
}
